In [ ]:
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression, Ridge

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

csv_file = '/content/drive/My Drive/TFG_AlienEmbarecRiadi/hotel_bookings_numeric.csv'
df = pd.read_csv(csv_file, delimiter=',')

data = df[['arrival_year_week','lead_time','total_stayed_nights','stays_in_weekend_nights', 'adr']].copy()
print(data.head(10))

   arrival_year_week  lead_time  total_stayed_nights  stays_in_weekend_nights    adr
0             201527        342                    0                        0    0.0
1             201527        737                    0                        0    0.0
2             201527          7                    1                        0   75.0
3             201527         13                    1                        0   75.0
4             201527         14                    2                        0   98.0
5             201527         14                    2                        0   98.0
6             201527          0                    2                        0  107.0
7             201527          9                    2                        0  103.0
8             201527         85                    3                        0   82.0
9             201527         75                    3                        0  105.5

In [1]:
datos_entrenamiento = data.sample(frac=0.8, random_state=0)
datos_test = data.drop(datos_entrenamiento.index)

etiquetas_entrenamiento = datos_entrenamiento.pop('adr')
etiquetas_test = datos_test.pop('adr')

print(etiquetas_entrenamiento)

NameError: ignored

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge


X_ent, X_test, y_ent, y_test = train_test_split(datos_entrenamiento, etiquetas_entrenamiento)

print('X_test ', X_test)
print('X_ent' , X_ent)
print('y_ent' , y_ent)
print('y_test' , y_test)
y_test.shape

X_test          arrival_year_week  lead_time  total_stayed_nights  stays_in_weekend_nights
17577              201542         12                    3                        1
25928              201628        175                    7                        2
115426             201727        405                    2                        0
118932             201734        457                    2                        0
59359              201644        475                    2                        0
...                   ...        ...                  ...                      ...
117546             201731        168                    5                        0
19776              201552         59                    8                        2
11592              201720         98                    8                        2
84069              201608        106                    3                        0
94002              201631        186                    2                        0

[23878 rows x 4 columns]
X_ent         arrival_year_week  lead_time  total_stayed_nights  stays_in_weekend_nights
24462              201621          3                    2                        0
29767              201645          8                    6                        2
8056               201637        363                    7                        2
69287              201722         59                    1                        1
113291             201722        104                    3                        1
...                   ...        ...                  ...                      ...
32243              201703         40                    3                        1
40588              201531          2                    3                        2
2542               201543         83                    3                        0
15073              201724          4                    1                        1
73172              201733        303                    1                        0

[71634 rows x 4 columns]
y_ent 24462      89.00
29767      51.04
8056      112.48
69287     140.00
113291    144.00
           ...
32243      55.00
40588      94.50
2542       41.98
15073     115.20
73172      99.90
Name: adr, Length: 71634, dtype: float64
y_test 17577      72.00
25928     115.20
115426    114.40
118932    122.40
59359      62.00
           ...
117546    130.50
19776      71.18
11592     123.00
84069      46.67
94002      96.30
Name: adr, Length: 23878, dtype: float64

(23878,)

In [ ]:
knn = KNeighborsRegressor(n_neighbors=100)
print('X_ent: ', X_ent)
print(y_ent)
knn.fit(X_ent,y_ent)

X_ent:          arrival_year_week  lead_time  total_stayed_nights  stays_in_weekend_nights
24462              201621          3                    2                        0
29767              201645          8                    6                        2
8056               201637        363                    7                        2
69287              201722         59                    1                        1
113291             201722        104                    3                        1
...                   ...        ...                  ...                      ...
32243              201703         40                    3                        1
40588              201531          2                    3                        2
2542               201543         83                    3                        0
15073              201724          4                    1                        1
73172              201733        303                    1                        0

[71634 rows x 4 columns]
24462      89.00
29767      51.04
8056      112.48
69287     140.00
113291    144.00
           ...
32243      55.00
40588      94.50
2542       41.98
15073     115.20
73172      99.90
Name: adr, Length: 71634, dtype: float64

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=100, p=2,
                    weights='uniform')

In [ ]:
knn.score(X_test,y_test)